version: '3.8'

services:
  app:
    image: assessment:latest # Replace with your application image
    container_name: app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose application port
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_H2_CONSOLE_ENABLED: "true" # Enable H2 console
